CREATE TABLE `Account` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `AccountNumber` varchar(100) DEFAULT NULL,
  `AccountSource` varchar(200) DEFAULT NULL,
  `AnnualRevenue` int(15) DEFAULT NULL,
  `AccountCurrency` varchar(200) DEFAULT NULL,
  `BillingCity` varchar(200) DEFAULT NULL,
  `BillingCountry` varchar(200) DEFAULT NULL,
  `BillingPostalCode` varchar(200) DEFAULT NULL,
  `BillingState` varchar(200) DEFAULT NULL,
  `BillingStreet` varchar(200) DEFAULT NULL,
  `Description` varchar(2000) DEFAULT NULL,
  `Fax` varchar(200) DEFAULT NULL,
  `Industry` varchar(200) DEFAULT NULL,
  `LastModifiedDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Name` varchar(200) DEFAULT NULL,
  `NumberOfEmployees` int(10) DEFAULT NULL,
  `OwnerId` varchar(200) DEFAULT NULL,
  `Ownership` varchar(200) DEFAULT NULL,
  `ParentId` varchar(200) DEFAULT NULL,
  `Phone` varchar(200) DEFAULT NULL,
  `Rating` varchar(200) DEFAULT NULL,
  `ShippingCity` varchar(200) DEFAULT NULL,
  `ShippingCountry` varchar(200) DEFAULT NULL,
  `ShippingPostalCode` varchar(200) DEFAULT NULL,
  `ShippingState` varchar(200) DEFAULT NULL,
  `ShippingStreet` varchar(200) DEFAULT NULL,
  `Sic` varchar(200) DEFAULT NULL,
  `SicDesc` varchar(200) DEFAULT NULL,
  `Site` varchar(200) DEFAULT NULL,
  `TickerSymbol` varchar(200) DEFAULT NULL,
  `Type` varchar(200) DEFAULT NULL,
  `Website` varchar(200) DEFAULT NULL,
  `SalesforceId` varchar(200) DEFAULT '',
  `LastModifiedById` varchar(200) NOT NULL DEFAULT 'mule@localhost',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
);

